# ncbi-datasets-cli || download reference genomes

# samtools=1.23.1      || to create bam file from sam file after minimap2
# minimap2      || fast aligner
# seqkit        || ??
# fastq         || quality trimming
# multiqc       || quality control report
# python3        || to run the resistance mutation calling script
# gatk4          || attempt to make variant calling without a custom script and without assuming diploidy like bcftools does
# r-optparse    || for report arguments